package com.medscope.intelligence.service;

import com.medscope.intelligence.entity.InsightPriority;
import com.medscope.intelligence.entity.InsightType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * One deterministic flag generated by PrioritizationEngine. The AI
 * receives these alongside the intelligence context to generate
 * natural-language insights grounded in structured evidence.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PrioritizationFlag {

    private InsightType type;
    private InsightPriority priority;
    private String testName;
    private List<Long> sourceResultIds;
    private String evidence;
}
